### ISSUE TITLE
the project or melody is only for  single (monophonic) pitch sequence?

### ISSUE THREAD

**Issue by ucasiggcas** [helenacuesta/MelodyExtraction#1]
Dear,
Could  it  be used in piano multi-tone/pitch music ?
Thx

**Comment by helenacuesta** [comment]
Hi,
Not really. These methods are designed for predominant melody extraction, which is one single pitch per frame of analysis.

**Comment by ucasiggcas** [comment]
Thanks at first.
But is it useful in Polyphonic Music?
Thx

**Comment by helenacuesta** [comment]
It can be used in polyphonic music and it will try to extract the predominant melody.
